---
title: "Presentation"
author: "Francesco"
date: "2020/02/20"
output:
  slidy_presentation: default
  html_document:
    number_sections: yes
    toc: yes
  ioslides_presentation: default
mode: selfcontained
subtitle: Developing Data Products Course Project
---


## Introduction

This presentation is part of the Developing Data Products Coursera.org course assignment.

It is an R Presentation generated with the R package slidify.

You can find the app to in this pitch here:
https://github.com/FRNCSCM/coursera_developing_data_products/tree/master/App


## Application Overview

- Shiny is a web application framework for R
- It helps you creating applications withouth any knowleadge in Javascript
- The source code consists of two files: server.R and ui.R
- server.R includes the the server logic of a Shiny web application
- ui.R includes the the user-interface logic

## How does it works? 

- Just open the server.R and ui.R files in your RStudio
- Push "Run App"" on the upper corner.
- Rstudio will automatically host your shiny project on your localhost (http://127.0.0.1:3656)

## The main panel

- First will show you a summary of the dataset mtcars.
- Second is a scattlerplot generated by plotly.
- Thirs is a table, showing the data sets data. The output's size depends on the inputted number in the side panel.

## The side panel

- The side panel consists of three elements
- two dropdowns menus: one for the x variable and one for the y variable. 
- Choosing your metrics will generate a plotly scatterplot.
- The third input is for the table. The value inputted are the amount of rows of the table displayed.
